DEBUG = False
ALLOWED_EXTENSIONS = 'xml'
PINGCASTLE_FOLDER = '/opt/pingchan/app/pingcastle/'
OUTPUT_FOLDER = '/opt/pingchan/app/pingcastle/output/'
UPLOAD_FOLDER = '/opt/pingchan/app/pingcastle/upload/'
REPORT_FOLDER= '/opt/pingchan/app/pingcastle/report/'
DATABASE_FILE = '/opt/pingchan/pingchan.db'
SECRET_KEY = '' # Change this value
SESSION_PERMANENT = False
SESSION_TYPE = "filesystem"
DOMAIN_NAME = "" # change this
SQLALCHEMY_TRACK_MODIFICATIONS = False
